/**
 * Document export utilities
 */

/**
 * Trigger a browser download of text content
 */
export function downloadTextFile(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Format a document for text export
 */
export function formatDocumentForExport(doc: {
    title: string;
    type: string;
    content: string;
    createdAt: string;
}): string {
    const divider = '='.repeat(60);

    return [
        divider,
        `DOCUMENT: ${doc.title}`,
        `TYPE: ${doc.type.replace(/_/g, ' ')}`,
        `GENERATED: ${new Date(doc.createdAt).toLocaleString()}`,
        `PLATFORM: LegalAI — AI-Powered Legal Assistant`,
        divider,
        '',
        doc.content,
        '',
        divider,
        'DISCLAIMER: This document was generated by AI and should be',
        'reviewed by a qualified legal professional before use.',
        divider,
    ].join('\n');
}

/**
 * Format a contract review for text export
 */
export function formatReviewForExport(review: {
    contractTitle: string;
    riskLevel: string;
    summary: string;
    clauses: string;
    createdAt: string;
}): string {
    const divider = '='.repeat(60);

    return [
        divider,
        `CONTRACT REVIEW: ${review.contractTitle}`,
        `RISK LEVEL: ${review.riskLevel}`,
        `REVIEWED: ${new Date(review.createdAt).toLocaleString()}`,
        `PLATFORM: LegalAI — AI-Powered Legal Assistant`,
        divider,
        '',
        'SUMMARY:',
        review.summary,
        '',
        'CLAUSE ANALYSIS:',
        review.clauses,
        '',
        divider,
        'DISCLAIMER: This analysis was generated by AI and should be',
        'reviewed by a qualified legal professional.',
        divider,
    ].join('\n');
}
