'use client';

import { Scale, AlertTriangle } from 'lucide-react';

interface LegalDisclaimerProps {
    type?: 'inline' | 'banner';
    text?: string;
}

const DEFAULT_TEXT =
    'This content was generated by AI and is for informational purposes only. It does not constitute legal advice. Please consult a qualified attorney for your specific situation.';

export default function LegalDisclaimer({
    type = 'inline',
    text = DEFAULT_TEXT,
}: LegalDisclaimerProps) {
    if (type === 'banner') {
        return (
            <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3">
                <div className="flex items-start gap-3">
                    <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
                    <div>
                        <p className="text-xs font-semibold text-amber-300">Legal Disclaimer</p>
                        <p className="mt-0.5 text-[11px] leading-relaxed text-amber-200/70">{text}</p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="flex items-center gap-2 text-[11px] text-surface-500">
            <Scale className="h-3 w-3 shrink-0" />
            <p>{text}</p>
        </div>
    );
}
